# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkadog < Formula
  desc "Kafka consumer/producer CLI"
  homepage "https://github.com/maximepeschard/kafkadog"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/maximepeschard/kafkadog/releases/download/v0.2.1/kafkadog_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "d5c031d0394a02961e6741240628673c9d77cb9e1e38fac03b6c9b77601ac565"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/maximepeschard/kafkadog/releases/download/v0.2.1/kafkadog_0.2.1_Linux_x86_64.tar.gz"
      sha256 "86dab6d99fd0fcb1aa7495f12657eb6ed1eee583d8e2521f7a85acb20cdacc10"
    end
  end

  def install
    bin.install "kafkadog"
  end
end
