# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkadog < Formula
  desc "Kafka consumer/producer CLI"
  homepage "https://github.com/maximepeschard/kafkadog"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/maximepeschard/kafkadog/releases/download/v0.4.0/kafkadog_0.4.0_Darwin_x86_64.tar.gz"
    sha256 "5df335b55070bdd4c87c7ba0a56c8f3dac8fbc0db72ec558aca415c598be973d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/maximepeschard/kafkadog/releases/download/v0.4.0/kafkadog_0.4.0_Linux_x86_64.tar.gz"
      sha256 "987238482c471d5c94515bf8d5cc872f83b3a6ac4e409bc522d90f592ef0dc5a"
    end
  end

  def install
    bin.install "kafkadog"
  end
end
